# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm7250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter avicii ebba,$(TARGET_DEVICE)),)

endif
